import { sha256 } from "../../../packages/core/src/hash.js";
import { BenchmarkRegistry } from "../../../packages/router/src/providerBenchmarks.js";
import { ProviderBenchmarkRunner } from "../../../packages/router/src/benchmarkRunner.js";
import { COMPUTE_BENCHMARK_CORPUS } from "../../../packages/router/src/benchmarkCorpus.js";
import { ProviderHealthManager } from "../../../packages/router/src/providerHealth.js";
import { ProviderRegistry } from "../../../packages/router/src/providerRegistry.js";
import { buildSeedMarket } from "../../../packages/router/src/providerSeeds.js";
import { D1ComputeMarketStore } from "../../../packages/router/src/computeStore.js";
import { DurableComputeGovernorClient } from "../../../packages/router/src/durableComputeGovernor.js";
import { ComputeMarketRouter } from "../../../packages/router/src/modelRouter.js";
import { ServiceModelGateway } from "../../../packages/router/src/serviceModelGateway.js";
import type { ComputeRequest, ProviderEvidenceRecord, TaskClass } from "../../../packages/router/src/computeTypes.js";
import type { Env } from "./runtime-types.js";
export async function buildComputeRuntime(env:Env){if(!env.MODELS||!env.COMPUTE_GOVERNOR)throw new Error("COMPUTE_RUNTIME_BINDINGS_REQUIRED");const seed=await buildSeedMarket(),store=new D1ComputeMarketStore(env.DB);let providers=await store.listProviders(),models=await store.listModels(),evidence=await store.listEvidence();if(providers.length===0){for(const p of seed.providers)await store.upsertProvider(p);for(const m of seed.models)await store.upsertModel(m);for(const e of seed.evidence)await store.addEvidence(e);providers=seed.providers;models=seed.models;evidence=seed.evidence;}const registry=new ProviderRegistry(providers,models,evidence);registry.refreshStates(new Date().toISOString());for(const p of registry.listProviders())await store.upsertProvider(p);for(const m of registry.listModels())await store.upsertModel(m);const id=env.COMPUTE_GOVERNOR.idFromName("global-compute-market"),governor=new DurableComputeGovernorClient(env.COMPUTE_GOVERNOR.get(id));for(const pool of seed.pools)await governor.configure(pool);const health=new ProviderHealthManager(),benchmarks=new BenchmarkRegistry();for(const b of await store.listBenchmarks())benchmarks.upsert(b);const gateway=new ServiceModelGateway(env.MODELS),router=new ComputeMarketRouter(registry,evidence,governor,health,benchmarks,gateway);return{router,store,registry,health,governor,gateway,benchmarks,evidence};}
export async function probeProvider(env:Env,providerId:string,modelId:string):Promise<{ok:boolean;evidence?:ProviderEvidenceRecord;detail:Record<string,unknown>}>{if(!env.MODELS)throw new Error("MODELS_SERVICE_BINDING_REQUIRED");const response=await env.MODELS.fetch("https://aria-models.internal/internal/probe",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({providerId,modelId})}),detail=await response.json() as Record<string,unknown>;if(!response.ok||detail.ok!==true)return{ok:false,detail};const now=new Date().toISOString(),evidence:ProviderEvidenceRecord={evidenceId:`live-probe:${providerId}:${(await sha256({providerId,modelId,now,detail})).slice(0,24)}`,providerId,modelId,evidenceClass:"LIVE_ACCOUNT_PROBE",claimType:"HEALTH",sourceIdentifier:`aria-models:${providerId}:${modelId}`,retrievedAt:now,expiresAt:new Date(Date.now()+15*60000).toISOString(),contentHash:await sha256(detail),result:"SUPPORTS",detail:"Credential-bound model probe succeeded; sanitized quota/usage metadata only."};return{ok:true,evidence,detail};}
export async function benchmarkProvider(env:Env,providerId:string,modelId:string,taskClasses?:TaskClass[]){const runtime=await buildComputeRuntime(env),now=new Date().toISOString(),runner=new ProviderBenchmarkRunner(runtime.registry,runtime.evidence,runtime.governor,runtime.gateway),classes=taskClasses??["EXTRACTION","CLASSIFICATION","STRUCTURED_JSON","BUSINESS_REASONING","AUD_CHALLENGE","CODING","SUMMARIZATION"] as TaskClass[],profiles=[];for(const taskClass of classes){const profile=await runner.run(providerId,modelId,taskClass,now);await runtime.store.recordBenchmark(profile,await sha256(COMPUTE_BENCHMARK_CORPUS.filter(c=>c.taskClass===taskClass)));profiles.push(profile);}return{profiles,qualified:profiles.every(p=>p.qualified),corpusCases:COMPUTE_BENCHMARK_CORPUS.length};}
export async function executeComputeRequest(env:Env,request:ComputeRequest){const runtime=await buildComputeRuntime(env),now=new Date().toISOString(),result=await runtime.router.run(request,now);await runtime.store.recordRoute(result.route);await runtime.store.recordReservation(result.reservation);return result;}
