import { AriaOrchestrator, type EffectDispatcher, type EffectDispatchResult } from "../../../packages/core/src/orchestrator.js";
import { sha256, stableId } from "../../../packages/core/src/hash.js";
import type { ActionClass, ActionIntent, ApprovalRequest, SystemState } from "../../../packages/core/src/types.js";
import { Scheduler, type ScheduledJobName } from "../../../packages/core/src/scheduler.js";
import { D1StateStore } from "../../../packages/memory/src/store.js";
import { WorkersAiProvider } from "../../../packages/router/src/modelRouter.js";
import { BudgetGovernor } from "../../../packages/router/src/budgetGovernor.js";
import { PolicyEngine } from "../../../packages/policy/src/policy.js";
import { createActionIntent } from "../../../packages/effects/src/kernel.js";
import { referenceEvents } from "../../../packages/fixtures/src/reference.js";
import { redactSecrets, WebhookIngestConnector } from "../../../packages/connectors/src/index.js";
import type { Env, MessageBatch, ServiceBindingLike } from "./runtime-types.js";
export { AriaCoordinator } from "./coordinator.js";
export { BusinessWorkflow } from "./workflow.js";
function securityHeaders(): HeadersInit { return { "content-type":"application/json; charset=utf-8","cache-control":"no-store","content-security-policy":"default-src 'none'; frame-ancestors 'none'","x-content-type-options":"nosniff","referrer-policy":"no-referrer" }; }
function json(body: unknown, status=200): Response { return new Response(JSON.stringify(redactSecrets(body)),{status,headers:securityHeaders()}); }
async function tokenHash(token:string):Promise<string>{const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(token));return [...new Uint8Array(digest)].map((b)=>b.toString(16).padStart(2,"0")).join("");}
async function authorized(request:Request,env:Env):Promise<boolean>{if(!env.ADMIN_TOKEN_HASH)return false;const token=request.headers.get("authorization")?.replace(/^Bearer\s+/i,"")??"";return Boolean(token)&&(await tokenHash(token))===env.ADMIN_TOKEN_HASH;}
async function withinRateLimit(env:Env,bucket:string,limit:number):Promise<boolean>{if(!env.COORDINATOR)return false;const stub=env.COORDINATOR.get(env.COORDINATOR.idFromName("global"));const response=await stub.fetch("https://coordinator.internal/rate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({bucket,limit,windowMs:60_000})});if(!response.ok)return false;return ((await response.json()) as {allowed?:boolean}).allowed===true;}
function configured(env:Env):{ready:boolean;missing:string[]}{const missing:string[]=[];if(!env.ADMIN_TOKEN_HASH)missing.push("ADMIN_TOKEN_HASH");if(!env.APPROVAL_SIGNING_KEY)missing.push("APPROVAL_SIGNING_KEY");if(!env.WEBHOOK_SECRET)missing.push("WEBHOOK_SECRET");if(!env.COORDINATOR)missing.push("COORDINATOR");if(!env.BUSINESS_WORKFLOW)missing.push("BUSINESS_WORKFLOW");if(!env.EFFECTS)missing.push("EFFECTS_SERVICE_BINDING");return{ready:missing.length===0,missing};}
async function businessPreconditionHash(state:SystemState):Promise<string>{return sha256({events:state.events.map((e)=>e.hash),leads:state.leads.map((l)=>({id:l.id,status:l.status,intent:l.intentScore,last:l.lastActivityAt})),knowledge:state.knowledge.map((k)=>({id:k.id,status:k.status,evidence:k.evidenceHash})),decisions:state.decisions.map((d)=>({id:d.id,priority:d.priority,verdict:d.auditVerdict}))});}
class ServiceEffectDispatcher implements EffectDispatcher {
  constructor(private readonly service:ServiceBindingLike){}
  async execute(intent:ActionIntent,approval:ApprovalRequest,currentPreconditionHash:string,now:string):Promise<EffectDispatchResult>{const response=await this.service.fetch("https://aria-effects.internal/internal/execute-intent",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({intent,approval,currentPreconditionHash,now})});const body=await response.json() as EffectDispatchResult&{error?:string};if(!response.ok)throw new Error(body.error??`EFFECT_GATEWAY_HTTP_${response.status}`);return body;}
}
async function dispatchApprovedIntent(orchestrator:AriaOrchestrator,env:Env,intent:ActionIntent,approval:ApprovalRequest):Promise<EffectDispatchResult>{
  if(!env.EFFECTS)throw new Error("EFFECTS_SERVICE_BINDING_REQUIRED");
  const currentPreconditionHash=await businessPreconditionHash(orchestrator.state);const result=await new ServiceEffectDispatcher(env.EFFECTS).execute(intent,approval,currentPreconditionHash,new Date().toISOString());
  if(result.receipt.status==="EXECUTED"){orchestrator.approvals.consume(approval.id,intent.actionDigest);intent.status="EXECUTED";if(!orchestrator.state.effectReceipts.some((r)=>r.receiptId===result.receipt.receiptId))orchestrator.state.effectReceipts.push(result.receipt);const action=orchestrator.state.actions.find((a)=>a.approvalId===approval.id);if(action)action.status="EXECUTED";}else intent.status="RETRYABLE";
  await orchestrator.persist();return result;
}
async function api(request:Request,env:Env):Promise<Response|null>{
  const url=new URL(request.url);if(!url.pathname.startsWith("/api/"))return null;const store=new D1StateStore(env.DB);
  if(request.method==="GET"&&url.pathname==="/api/health"){const cfg=configured(env);return json({ok:cfg.ready,service:"AriaOS",worker:"aria-core",environment:env.ENVIRONMENT??"unknown",sha:env.ARIA_GIT_SHA??"unknown",canonicalMemory:"D1",effectBoundary:"SERVICE_BINDING_ONLY",agentWriteCredentials:0,costPolicy:"ZERO_SPEND_HARD_LOCK",missingBindings:cfg.missing},cfg.ready?200:503);}
  if(request.method==="GET"&&url.pathname==="/api/system/budget")return json(new BudgetGovernor().snapshot());
  if(request.method==="GET"&&url.pathname==="/api/system/policy")return json(new PolicyEngine().policyMatrix());
  if(request.method==="GET"&&url.pathname==="/api/state")return json(await store.load());
  if(request.method!=="GET"){if(!(await withinRateLimit(env,`admin:${url.pathname}`,30)))return json({error:"RATE_LIMITED_OR_COORDINATOR_UNAVAILABLE"},429);if(!(await authorized(request,env)))return json({error:"ADMIN_AUTH_REQUIRED"},401);}
  if(request.method==="POST"&&url.pathname==="/api/actions/request"){
    if(!env.APPROVAL_SIGNING_KEY)return json({error:"APPROVAL_SIGNING_KEY_REQUIRED"},503);
    const body=await request.json() as {actionClass?:ActionClass;payload?:Record<string,unknown>;reason?:string;requestedBy?:"CEO"|"RESEARCH"|"CMO"|"SALES"|"DATA"|"DEV"|"AUD";connector?:string;operation?:string;target?:string;subjectId?:string;taskId?:string};
    const classes:ActionClass[]=["READ_PUBLIC","READ_PRIVATE","INTERNAL_WRITE","DRAFT_EXTERNAL","SEND_EXTERNAL","PUBLISH_CONTENT","MONEY_MUTATION","DESTRUCTIVE_MUTATION","CREDENTIAL_MUTATION","CODE_WRITE","CODE_MERGE","DEPLOY"];
    if(!body.actionClass||!classes.includes(body.actionClass)||!body.payload||typeof body.payload!=="object")return json({error:"ACTION_SCHEMA_INVALID"},400);
    const requestedBy=body.requestedBy??"CEO",policy=new PolicyEngine(),decision=policy.decision(body.actionClass);const orchestrator=new AriaOrchestrator(store,new WorkersAiProvider(env.AI),env.APPROVAL_SIGNING_KEY);await orchestrator.load();
    if(decision==="DENY")return json({error:"ACTION_DENIED_BY_POLICY",actionClass:body.actionClass},403);
    if(decision==="ALLOW"){const id=await stableId("action",{actionClass:body.actionClass,payload:body.payload,at:Date.now()});orchestrator.state.actions.push({id,actionClass:body.actionClass,payload:structuredClone(body.payload),requestedBy,policyDecision:decision,status:"DRAFT",createdAt:new Date().toISOString()});await orchestrator.persist();return json({id,policyDecision:decision,status:"DRAFT",externalEffect:false},201);}
    const now=new Date(),preconditionHash=await businessPreconditionHash(orchestrator.state);const intent=await createActionIntent({taskId:body.taskId??await stableId("task",{requestedBy,at:now.toISOString()}),agentId:requestedBy,subjectId:body.subjectId??"business",actionClass:body.actionClass,connector:body.connector??"safe-outbound",operation:body.operation??"send",target:body.target??String(body.payload.to??"unspecified"),canonicalParameters:body.payload,justification:String(body.reason??"protected action").slice(0,512),evidenceRefs:[],preconditionHash,idempotencyKey:await stableId("idem",{requestedBy,body:body.payload,at:now.toISOString()}),requestedAt:now.toISOString(),expiresAt:new Date(now.getTime()+15*60_000).toISOString()});
    intent.status="APPROVAL_REQUIRED";await store.commitStateAndIntent(orchestrator.state,intent);orchestrator.state.actionIntents.push(intent);const approval=await orchestrator.approvals.request({actionClass:body.actionClass,requestedBy,reason:intent.justification,scope:"action-digest",actionDigest:intent.actionDigest,policyVersion:intent.policyVersion,approvalChainVersion:intent.approvalChainVersion});intent.approvalId=approval.id;
    const actionId=await stableId("action",{intentId:intent.intentId});orchestrator.state.actions.push({id:actionId,actionClass:body.actionClass,payload:structuredClone(body.payload),requestedBy,policyDecision:decision,approvalId:approval.id,status:"BLOCKED",createdAt:now.toISOString()});await store.commitStateAndIntent(orchestrator.state,intent);orchestrator.state.approvals=orchestrator.approvals.list();await orchestrator.persist();if(env.BUSINESS_WORKFLOW)await env.BUSINESS_WORKFLOW.create({id:approval.id,params:{taskId:actionId,kind:body.actionClass,approvalId:approval.id}});return json({actionId,intentId:intent.intentId,actionDigest:intent.actionDigest,approvalId:approval.id,policyDecision:decision,status:"PENDING_APPROVAL"},202);
  }
  if(request.method==="POST"&&url.pathname==="/api/reference-e2e"){if(!env.APPROVAL_SIGNING_KEY||!env.EFFECTS)return json({error:"LIVE_BINDINGS_REQUIRED"},503);const orchestrator=new AriaOrchestrator(store,new WorkersAiProvider(env.AI),env.APPROVAL_SIGNING_KEY,()=>new Date("2026-08-19T15:00:00.000Z"));await orchestrator.load();const result=await orchestrator.runReferenceE2E(await referenceEvents(),new ServiceEffectDispatcher(env.EFFECTS));return json({...result,state:undefined});}
  const approvalMatch=url.pathname.match(/^\/api\/approvals\/([^/]+)\/(approve|reject)$/);
  if(request.method==="POST"&&approvalMatch){
    if(!env.APPROVAL_SIGNING_KEY)return json({error:"APPROVAL_SIGNING_KEY_REQUIRED"},503);const orchestrator=new AriaOrchestrator(store,new WorkersAiProvider(env.AI),env.APPROVAL_SIGNING_KEY);await orchestrator.load();const id=decodeURIComponent(approvalMatch[1]!),operation=approvalMatch[2]!;
    try{const body=await request.json() as {actor?:string};const actor=String(body.actor??"cockpit-human").slice(0,128);const result=operation==="approve"?await orchestrator.approvals.approve(id,actor):orchestrator.approvals.reject(id,actor);orchestrator.state.approvals=orchestrator.approvals.list();await orchestrator.persist();if(env.BUSINESS_WORKFLOW){try{await env.BUSINESS_WORKFLOW.get(id).sendEvent({type:"approval",payload:{approvalId:id,decision:operation==="approve"?"APPROVED":"REJECTED"}})}catch{}}
      if(operation==="approve"){const intent=orchestrator.state.actionIntents.find((v)=>v.approvalId===id);if(!intent)return json({error:"APPROVAL_INTENT_NOT_FOUND"},409);try{const effect=await dispatchApprovedIntent(orchestrator,env,intent,result);return json({approval:orchestrator.approvals.get(id),intent,effect});}catch(error){intent.status="RETRYABLE";await store.commitStateAndIntent(orchestrator.state,intent);return json({approval:result,intent,error:error instanceof Error?error.message:"EFFECT_DISPATCH_FAILED",status:"RETRYABLE"},409);}}
      return json(result);
    }catch(error){return json({error:error instanceof Error?error.message:"APPROVAL_ERROR"},400);}
  }
  if(request.method==="POST"&&url.pathname==="/api/ingest/webhook"){if(!env.WEBHOOK_SECRET)return json({error:"WEBHOOK_NOT_CONFIGURED"},503);const raw=await request.text(),signature=request.headers.get("x-aria-signature")??"";try{const event=await new WebhookIngestConnector(env.WEBHOOK_SECRET).parse(raw,signature);if(env.EVENTS_QUEUE)await env.EVENTS_QUEUE.send({kind:"event",event});else return json({error:"EVENT_QUEUE_NOT_CONFIGURED"},503);return json({accepted:true,id:event.id},202);}catch(error){return json({error:error instanceof Error?error.message:"INGEST_ERROR"},400);}}
  return json({error:"NOT_FOUND"},404);
}
const CRON_JOB:Record<string,ScheduledJobName>={"*/15 * * * *":"business_tick","0 14 * * 1-5":"daily_ceo","0 6 * * *":"nightly_memory","0 10 * * 0":"weekly_security"};
export default {
  async fetch(request:Request,env:Env):Promise<Response>{const r=await api(request,env);if(r)return r;if(env.ASSETS)return env.ASSETS.fetch(request);return new Response("AriaOS cockpit assets not bound",{status:503});},
  async scheduled(controller:{cron?:string;scheduledTime?:number},env:Env):Promise<void>{const name=CRON_JOB[controller.cron??""]??"business_tick",slot=new Date(controller.scheduledTime??Date.now()).toISOString(),store=new D1StateStore(env.DB),state=await store.load(),scheduler=new Scheduler(state),queued=await scheduler.enqueue(name,slot);await store.save(state);if(!queued.duplicate&&env.EVENTS_QUEUE)await env.EVENTS_QUEUE.send({kind:"scheduled",taskId:queued.task.id,job:name,slot});},
  async queue(batch:MessageBatch,env:Env):Promise<void>{const store=new D1StateStore(env.DB);for(const message of batch.messages){try{const body=message.body as {kind?:string;taskId?:string};if(body.kind==="scheduled"&&body.taskId){const state=await store.load(),task=state.tasks.find((v)=>v.id===body.taskId);if(!task)throw new Error("SCHEDULED_TASK_NOT_FOUND");if(task.status==="DONE"){message.ack();continue;}task.status="RUNNING";await store.save(state);if(env.BUSINESS_WORKFLOW)await env.BUSINESS_WORKFLOW.create({id:task.id,params:{taskId:task.id,kind:task.type}});else throw new Error("BUSINESS_WORKFLOW_NOT_CONFIGURED");task.status="DONE";await store.save(state);message.ack();continue;}if(body.kind==="event"){message.ack();continue;}throw new Error("QUEUE_MESSAGE_SCHEMA_INVALID");}catch{message.retry({delaySeconds:30});}}}
};
