import test from 'node:test';
import assert from 'node:assert/strict';
import modelWorker from '../dist/apps/model-worker/src/index.js';
import { manifestConfigHash, findManifest } from '../dist/apps/model-worker/src/providerManifest.js';
import { sha256 } from '../dist/packages/core/src/hash.js';
const NOW=()=>new Date();
async function execution(overrides={}){const providerId='cloudflare-workers-ai',modelId='@cf/zai-org/glm-4.7-flash',provider=findManifest(providerId),prompt='public fixture',promptHash=await sha256(prompt),base={executionId:'e1',reservationId:'r1',taskId:'t1',role:'DATA',dataClass:'PUBLIC',providerId,modelId,adapterVersion:'aria-model-gateway-v1',providerConfigHash:await manifestConfigHash(provider),prompt,promptHash,maxOutputTokens:32,requiredCapabilities:['text'],policyVersion:'aria-compute-policy-v1',routeDecisionId:'rd1',requestedAt:NOW().toISOString(),expiresAt:new Date(Date.now()+60000).toISOString(),...overrides};return{...base,executionDigest:await sha256(base)};}
const ai={run:async(_model,input)=>({response:String(input.prompt)==='public fixture'?'OK':'OK',usage:{prompt_tokens:3,completion_tokens:1},finish_reason:'stop'})};
const env={AI:ai,ARIA_GIT_SHA:'a'.repeat(40)};
async function call(path,body,customEnv=env){return modelWorker.fetch(new Request(`https://internal${path}`,{method:body?'POST':'GET',headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined}),customEnv);}
test('aria-models executes typed manifest-bound Workers AI request',async()=>{const ex=await execution(),r=await call('/internal/infer',ex);assert.equal(r.status,200);const body=await r.json();assert.equal(body.receipt.status,'SUCCESS');assert.equal(body.receipt.providerId,'cloudflare-workers-ai');assert.equal(body.text,'OK');});
test('aria-models rejects unknown provider and unknown model',async()=>{const a=await execution({providerId:'unknown'});a.executionDigest=await sha256(Object.fromEntries(Object.entries(a).filter(([k])=>k!=='executionDigest')));let r=await call('/internal/infer',a);assert.equal(r.status,400);assert.match((await r.json()).error,/UNKNOWN_PROVIDER/);const b=await execution({modelId:'nope'});b.executionDigest=await sha256(Object.fromEntries(Object.entries(b).filter(([k])=>k!=='executionDigest')));r=await call('/internal/infer',b);assert.match((await r.json()).error,/UNKNOWN_MODEL/);});
test('aria-models rejects config drift, expiry, output expansion and unsupported capability',async()=>{let ex=await execution({providerConfigHash:'bad'});ex.executionDigest=await sha256(Object.fromEntries(Object.entries(ex).filter(([k])=>k!=='executionDigest')));let r=await call('/internal/infer',ex);assert.match((await r.json()).error,/CONFIG_HASH_MISMATCH/);ex=await execution({expiresAt:'2020-01-01T00:00:00Z'});r=await call('/internal/infer',ex);assert.match((await r.json()).error,/EXPIRED_EXECUTION/);ex=await execution({maxOutputTokens:999999});r=await call('/internal/infer',ex);assert.match((await r.json()).error,/MAX_OUTPUT/);ex=await execution({requiredCapabilities:['vision']});r=await call('/internal/infer',ex);assert.match((await r.json()).error,/UNSUPPORTED_CAPABILITY/);});
test('aria-models defense-in-depth denies secret prompt',async()=>{const prompt='api_key=abcdef123456',ex=await execution({prompt,promptHash:await sha256(prompt)});ex.executionDigest=await sha256(Object.fromEntries(Object.entries(ex).filter(([k])=>k!=='executionDigest')));const r=await call('/internal/infer',ex);assert.match((await r.json()).error,/SECRET_DATA_MODEL_DENIED/);});
test('model provider credential presence endpoint exposes booleans only',async()=>{const r=await call('/internal/health');const body=await r.json();assert.equal(body.valuesExposed,false);assert.deepEqual(body.providerCredentialPresence,{groq:false,mistral:false,gemini:false,zenmux:false});assert.equal(JSON.stringify(body).includes('secret-value'),false);});
test('external provider probe fails closed when model credential absent',async()=>{const r=await call('/internal/probe',{providerId:'groq',modelId:'openai/gpt-oss-120b'});assert.equal(r.status,401);const body=await r.json();assert.equal(body.credentialPresent,false);assert.equal(body.valuesExposed,false);});
test('external 402 returns BILLING_REQUIRED and never reports successful receipt',async()=>{let calls=0;const fetcher=async()=>{calls++;return new Response('pay',{status:402})};const original=globalThis.fetch;globalThis.fetch=fetcher;try{const ex=await execution({providerId:'groq',modelId:'openai/gpt-oss-120b',providerConfigHash:await manifestConfigHash(findManifest('groq'))});ex.executionDigest=await sha256(Object.fromEntries(Object.entries(ex).filter(([k])=>k!=='executionDigest')));const r=await call('/internal/infer',ex,{...env,GROQ_API_KEY:'test-only'});assert.equal(r.status,402);const body=await r.json();assert.equal(body.receipt.errorClass,'BILLING_REQUIRED');assert.equal(calls,1);}finally{globalThis.fetch=original;}});
