import type { TaskClass } from "./computeTypes.js";
export interface BenchmarkCase{id:string;taskClass:TaskClass;prompt:string;expected:string;}
const definitions:Record<TaskClass,Array<[string,string]>>={
 EXTRACTION:[["Name: Ana; City: Santa Fe","Ana"],["Order id=42 status=paid","42"],["Email foo@example.com","foo@example.com"],["Total USD 17","17"],["Date 2026-08-19","2026-08-19"],["SKU ABC-9 qty 4","ABC-9"],["Lead score 91","91"],["Country Argentina","Argentina"],["Plan FREE","FREE"],["Version v3","v3"]],
 CLASSIFICATION:[["invoice settled","PAID"],["lead asks price today","HOT"],["server 500 error","INCIDENT"],["draft blog post","CONTENT"],["API key leaked","SECRET"],["public press release","PUBLIC"],["internal sales notes","INTERNAL"],["customer contract","CONFIDENTIAL"],["429 too many requests","RATE_LIMIT"],["model not found","MODEL_MISSING"]],
 STRUCTURED_JSON:[["key=a value=1",'{"key":"a","value":1}'],["key=b value=2",'{"key":"b","value":2}'],["key=c value=3",'{"key":"c","value":3}'],["key=d value=4",'{"key":"d","value":4}'],["key=e value=5",'{"key":"e","value":5}'],["key=f value=6",'{"key":"f","value":6}'],["key=g value=7",'{"key":"g","value":7}'],["key=h value=8",'{"key":"h","value":8}'],["key=i value=9",'{"key":"i","value":9}'],["key=j value=10",'{"key":"j","value":10}']],
 BUSINESS_REASONING:[["revenue fell and conversion halved","INVESTIGATE_CONVERSION"],["one hot lead and no anomaly","FOLLOW_UP_HOT_LEAD"],["quota at hard cap","DEFER_OPTIONAL_WORK"],["price changed above zero","DISABLE_ROUTE"],["evidence expired","REFRESH_EVIDENCE"],["two providers healthy","USE_BEST_SAFE_ROUTE"],["approval digest changed","REQUIRE_NEW_APPROVAL"],["provider returns 402","DISABLE_BILLING_RISK"],["all model routes unsafe","NO_SAFE_MODEL_ROUTE"],["duplicate event arrives","DEDUPLICATE"]],
 AUD_CHALLENGE:[["claim has no source","FAIL"],["source current and first party","PASS"],["source expired","UNCERTAIN"],["price from social post only","FAIL"],["billing mode unknown","FAIL"],["private data to training provider","FAIL"],["secret token in prompt","FAIL"],["approval reused","FAIL"],["ledger hash matches","PASS"],["live claim without deployment","FAIL"]],
 CODING:[["return JS expression for one plus one","1+1"],["SQL select all from leads","SELECT * FROM leads"],["HTTP method to read resource","GET"],["HTTP code for rate limit","429"],["HTTP code payment required","402"],["hash algorithm required","SHA-256"],["transactional outbox store","D1"],["private worker link","Service Binding"],["TS strict boolean literal","true"],["JSON null literal","null"]],
 SUMMARIZATION:[["A is healthy. B is down.","A healthy; B down"],["Cost is zero. Paid fallback denied.","Zero cost; no paid fallback"],["Evidence expired; route disabled.","Expired evidence disabled route"],["Quota exhausted; task deferred.","Quota exhausted; defer task"],["Approval consumed once.","Approval one-time"],["Secret detected; model denied.","Secret denied"],["Groq healthy; Cloudflare rate-limited.","Groq healthy; Cloudflare rate-limited"],["Ledger verified; tamper detected.","Ledger verified; tamper detected"],["Model removed; fallback safe.","Model removed; safe fallback"],["All unsafe; no route.","No safe route"]]
};
export const COMPUTE_BENCHMARK_CORPUS:BenchmarkCase[]=Object.entries(definitions).flatMap(([taskClass,cases])=>cases.map(([input,expected],i)=>({id:`${taskClass.toLowerCase()}-${i+1}`,taskClass:taskClass as TaskClass,prompt:`Respond with only this benchmark answer. Input: ${input}.`,expected})));
