import type { ComputeReservation, QuotaPool } from "./computeTypes.js";
export interface ReservationRequest{routeDecisionId:string;providerId:string;modelId:string;quotaPoolId:string;estimatedInput:number;reservedOutput:number;reservedUsageUnits:number;idempotencyKey:string;now:string;ttlMs?:number;}
export interface ComputeGovernor{reserve(request:ReservationRequest):Promise<ComputeReservation>;commit(reservationId:string,actualUsage:number,now:string):Promise<ComputeReservation>;release(reservationId:string,now:string):Promise<ComputeReservation>;expire(now:string):Promise<number>;get(reservationId:string):Promise<ComputeReservation|undefined>;list():Promise<ComputeReservation[]>;pool(id:string):Promise<QuotaPool|undefined>;}
function syncId(value:string):string{let h=2166136261;for(let i=0;i<value.length;i++){h^=value.charCodeAt(i);h=Math.imul(h,16777619);}return`compute-res-${(h>>>0).toString(16).padStart(8,"0")}`;}
export class InMemoryComputeGovernor implements ComputeGovernor{
 private pools=new Map<string,QuotaPool>();private reservations=new Map<string,ComputeReservation>();private idem=new Map<string,string>();
 constructor(pools:QuotaPool[]){for(const p of pools){if(p.localHardFraction>0.8)throw new Error("QUOTA_HARD_FRACTION_EXCEEDS_80_PERCENT");this.pools.set(p.quotaPoolId,structuredClone(p));}}
 async reserve(r:ReservationRequest):Promise<ComputeReservation>{const existingId=this.idem.get(r.idempotencyKey);if(existingId)return structuredClone(this.reservations.get(existingId)!);const p=this.pools.get(r.quotaPoolId);if(!p)throw new Error("RESERVATION_FAILED:QUOTA_POOL_UNKNOWN");if(p.providerId!==r.providerId||(p.modelId&&p.modelId!==r.modelId))throw new Error("RESERVATION_FAILED:POOL_ROUTE_MISMATCH");if(p.verifiedFreeCeiling===null)throw new Error("RESERVATION_FAILED:QUOTA_UNKNOWN");const usable=p.verifiedFreeCeiling*p.localHardFraction,upstream=p.upstreamRemaining===undefined?Infinity:p.upstreamRemaining;if(p.consumed+p.reserved+r.reservedUsageUnits>usable||r.reservedUsageUnits>upstream)throw new Error("FREE_QUOTA_EXHAUSTED");const reservationId=syncId(`${r.idempotencyKey}:${r.routeDecisionId}`),expiresAt=new Date(new Date(r.now).getTime()+(r.ttlMs??120000)).toISOString(),reservation:ComputeReservation={reservationId,idempotencyKey:r.idempotencyKey,routeDecisionId:r.routeDecisionId,providerId:r.providerId,modelId:r.modelId,quotaPoolId:r.quotaPoolId,estimatedInput:r.estimatedInput,reservedOutput:r.reservedOutput,reservedUsageUnits:r.reservedUsageUnits,createdAt:r.now,expiresAt,status:"RESERVED"};p.reserved+=r.reservedUsageUnits;this.pools.set(p.quotaPoolId,p);this.reservations.set(reservationId,reservation);this.idem.set(r.idempotencyKey,reservationId);return structuredClone(reservation);}
 async commit(id:string,actualUsage:number,now:string):Promise<ComputeReservation>{if(!Number.isFinite(actualUsage)||actualUsage<0)throw new Error("INVALID_ACTUAL_USAGE");const r=this.reservations.get(id);if(!r)throw new Error("RESERVATION_NOT_FOUND");if(r.status==="COMMITTED")return structuredClone(r);if(r.status!=="RESERVED"&&r.status!=="FAILED")throw new Error(`RESERVATION_NOT_COMMITTABLE:${r.status}`);const p=this.pools.get(r.quotaPoolId)!;p.reserved=Math.max(0,p.reserved-r.reservedUsageUnits);p.consumed+=Math.max(actualUsage,r.uncertainty==="UNKNOWN_COMPLETION"?r.reservedUsageUnits:0);r.actualUsage=actualUsage;r.status="COMMITTED";this.pools.set(p.quotaPoolId,p);this.reservations.set(id,r);void now;return structuredClone(r);}
 async release(id:string,now:string):Promise<ComputeReservation>{const r=this.reservations.get(id);if(!r)throw new Error("RESERVATION_NOT_FOUND");if(r.status==="RELEASED")return structuredClone(r);if(r.status!=="RESERVED")throw new Error(`RESERVATION_NOT_RELEASABLE:${r.status}`);const p=this.pools.get(r.quotaPoolId)!;p.reserved=Math.max(0,p.reserved-r.reservedUsageUnits);r.status="RELEASED";this.pools.set(p.quotaPoolId,p);this.reservations.set(id,r);void now;return structuredClone(r);}
 async markUnknown(id:string):Promise<void>{const r=this.reservations.get(id);if(!r)throw new Error("RESERVATION_NOT_FOUND");r.status="FAILED";r.uncertainty="UNKNOWN_COMPLETION";this.reservations.set(id,r);}
 async expire(now:string):Promise<number>{let n=0;for(const r of this.reservations.values())if(r.status==="RESERVED"&&r.expiresAt<=now){const p=this.pools.get(r.quotaPoolId)!;p.reserved=Math.max(0,p.reserved-r.reservedUsageUnits);r.status="EXPIRED";n++;}return n;}
 async get(id:string):Promise<ComputeReservation|undefined>{const r=this.reservations.get(id);return r?structuredClone(r):undefined;}async list():Promise<ComputeReservation[]>{return[...this.reservations.values()].map(x=>structuredClone(x));}async pool(id:string):Promise<QuotaPool|undefined>{const p=this.pools.get(id);return p?structuredClone(p):undefined;}
}
