import { sha256, stableId } from "../../core/src/hash.js";
import type { ComputeProviderRecord, EvidenceClass, ProviderEvidenceRecord } from "./computeTypes.js";
export const MAX_EVIDENCE_TTL_MS={RECURRING_FREE:14*86_400_000,PROMOTIONAL_FREE:24*3_600_000,SIGNUP_GRANT:3_600_000,TRIAL:3_600_000,LOCAL_ZERO_COST:14*86_400_000,UNKNOWN:0,PAID:0,LIVE_HEALTH:15*60_000,MODEL_CATALOG_RECURRING:7*86_400_000,MODEL_CATALOG_PROMO:24*3_600_000,PRIVACY_TOS:14*86_400_000} as const;
const authoritative=new Set<EvidenceClass>(["FIRST_PARTY_OFFICIAL_DOC","FIRST_PARTY_API","FIRST_PARTY_DASHBOARD_OBSERVED","FIRST_PARTY_TERMS","SOURCE_CODE_OFFICIAL","LIVE_ACCOUNT_PROBE"]);
export function isFirstPartyEvidence(e:EvidenceClass):boolean{return authoritative.has(e);}export function isEvidenceFresh(e:ProviderEvidenceRecord,now:string):boolean{return e.expiresAt>now&&e.retrievedAt<=now;}export function evidenceAgeMs(e:ProviderEvidenceRecord,now:string):number{return Math.max(0,new Date(now).getTime()-new Date(e.retrievedAt).getTime());}
export function validateEvidenceTtl(provider:ComputeProviderRecord,e:ProviderEvidenceRecord):boolean{const duration=new Date(e.expiresAt).getTime()-new Date(e.retrievedAt).getTime();let max=MAX_EVIDENCE_TTL_MS[provider.freeType];if(e.claimType==="HEALTH")max=MAX_EVIDENCE_TTL_MS.LIVE_HEALTH;if(e.claimType==="PRIVACY"||e.claimType==="TOS")max=MAX_EVIDENCE_TTL_MS.PRIVACY_TOS;if(e.claimType==="CATALOG")max=provider.freeType==="PROMOTIONAL_FREE"?MAX_EVIDENCE_TTL_MS.MODEL_CATALOG_PROMO:MAX_EVIDENCE_TTL_MS.MODEL_CATALOG_RECURRING;return duration>=0&&duration<=max;}
export function activatingEvidence(provider:ComputeProviderRecord,evidence:ProviderEvidenceRecord[],now:string):{ok:boolean;missing:string[]}{const valid=evidence.filter(x=>x.providerId===provider.providerId&&x.result==="SUPPORTS"&&isFirstPartyEvidence(x.evidenceClass)&&isEvidenceFresh(x,now)&&validateEvidenceTtl(provider,x));const types=new Set(valid.map(x=>x.claimType));const missing=["PRICE","BILLING","PRIVACY","TOS","CATALOG"].filter(type=>!types.has(type as ProviderEvidenceRecord["claimType"]));if(provider.credentialBindingName&&!valid.some(x=>x.evidenceClass==="LIVE_ACCOUNT_PROBE"&&x.claimType==="HEALTH"))missing.push("LIVE_ACCOUNT_PROBE");return{ok:missing.length===0,missing};}
export async function createEvidence(input:Omit<ProviderEvidenceRecord,"evidenceId"|"contentHash">&{content:unknown}):Promise<ProviderEvidenceRecord>{const contentHash=await sha256(input.content);const evidenceId=await stableId("compute-evidence",{providerId:input.providerId,modelId:input.modelId,claimType:input.claimType,source:input.sourceIdentifier,contentHash,retrievedAt:input.retrievedAt});const{content:_content,...rest}=input;return{...rest,evidenceId,contentHash};}
export function discoverCandidate(providerId:string,sourceIdentifier:string,retrievedAt:string,expiresAt:string,contentHash:string):ProviderEvidenceRecord{return{evidenceId:`candidate:${providerId}:${contentHash.slice(0,12)}`,providerId,evidenceClass:"THIRD_PARTY_CATALOG",claimType:"CATALOG",sourceIdentifier,retrievedAt,expiresAt,contentHash,result:"CANDIDATE_ONLY",detail:"Candidate discovery only; cannot activate production route"};}
