#!/usr/bin/env node
import fs from 'node:fs';import { spawnSync } from 'node:child_process';
import { emptyState } from '../dist/packages/memory/src/store.js';import { EventMemory, Ledger, rebuildProjection, stateHash } from '../dist/packages/memory/src/ledger.js';import { referenceEvents } from '../dist/packages/fixtures/src/reference.js';import { LocalEffectGateway } from '../dist/packages/effects/src/local.js';import { AriaOrchestrator } from '../dist/packages/core/src/orchestrator.js';import { Scheduler } from '../dist/packages/core/src/scheduler.js';import { buildSeedMarket } from '../dist/packages/router/src/providerSeeds.js';import { ProviderRegistry } from '../dist/packages/router/src/providerRegistry.js';import { InMemoryComputeGovernor } from '../dist/packages/router/src/computeGovernor.js';import { ProviderHealthManager } from '../dist/packages/router/src/providerHealth.js';import { BenchmarkRegistry } from '../dist/packages/router/src/providerBenchmarks.js';import { ComputeMarketRouter } from '../dist/packages/router/src/modelRouter.js';import { sha256 } from '../dist/packages/core/src/hash.js';
const dir='.aria',file=`${dir}/local-state.json`,ledgerFile=`${dir}/local-ledger.json`,disabledFile=`${dir}/compute-disabled.json`;class FileStore{async load(){return fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):emptyState()}async save(s){fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(file,JSON.stringify(s,null,2)+'\n')}async reset(){fs.rmSync(dir,{recursive:true,force:true})}async loadLedger(){return fs.existsSync(ledgerFile)?JSON.parse(fs.readFileSync(ledgerFile,'utf8')):[]}async saveLedger(r){fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(ledgerFile,JSON.stringify(r,null,2)+'\n')}}
const command=process.argv[2]??'help',store=new FileStore(),run=args=>{const r=spawnSync('npm',args,{stdio:'inherit'});process.exitCode=r.status??1};
async function computeCli(){const sub=process.argv[3]??'status',seed=await buildSeedMarket(),registry=new ProviderRegistry(seed.providers,seed.models,seed.evidence),now=new Date().toISOString();registry.refreshStates(now);const disabled=fs.existsSync(disabledFile)?JSON.parse(fs.readFileSync(disabledFile,'utf8')):[];for(const id of disabled)registry.disable(id,'LOCAL_OPERATOR_KILL');
 if(sub==='status'){console.log(JSON.stringify({providers:registry.listProviders().length,models:registry.listModels().length,activeProviders:registry.listProviders().filter(p=>p.productionEligible).map(p=>p.providerId),costHardCapUsd:0,paidFallback:'DENY',secretDataToModel:'DENY'},null,2));return;}
 if(sub==='providers'){console.log(JSON.stringify(registry.listProviders().map(p=>({providerId:p.providerId,providerName:p.providerName,freeType:p.freeType,billingSafety:p.billingSafety,trustClass:p.trustClass,privacyClass:p.privacyClass,routeState:p.routeState,productionEligible:p.productionEligible,lastVerifiedAt:p.lastVerifiedAt,verificationExpiresAt:p.verificationExpiresAt})),null,2));return;}
 if(sub==='probe'){const provider=process.argv[4];if(!provider)throw new Error('PROVIDER_REQUIRED');console.log(JSON.stringify({provider,status:'LIVE_PROBE_REQUIRES_DEPLOYED_ARIA_MODELS',command:`POST /api/compute/probe/${provider}`,credentialValuesExposed:false},null,2));return;}
 if(sub==='benchmark'){run(['run','benchmark:compute']);return;}
 if(sub==='verify-cost'){console.log(JSON.stringify({COST_HARD_CAP_USD:0,MODEL_SPEND_AUTHORIZED_USD:0,BILLABLE_INFERENCE:'DENY',UNKNOWN_PRICE:'DENY',UNKNOWN_BILLING_SAFETY:'DENY',PAID_FALLBACK:'DENY'},null,2));return;}
 if(sub==='disable'){const id=process.argv[4];if(!id)throw new Error('PROVIDER_OR_MODEL_REQUIRED');fs.mkdirSync(dir,{recursive:true});const next=[...new Set([...disabled,id])];fs.writeFileSync(disabledFile,JSON.stringify(next,null,2)+'\n');console.log(JSON.stringify({disabled:id,durableLocal:true,productionApi:`POST /api/compute/disable/${id}`},null,2));return;}
 if(sub==='reconcile'){const stale=registry.listProviders().filter(p=>p.verificationExpiresAt<=now).map(p=>p.providerId),candidates=registry.listProviders().filter(p=>!p.productionEligible).map(p=>({providerId:p.providerId,state:p.routeState}));console.log(JSON.stringify({now,stale,candidates,action:'stale routes disabled; live account probes required where configured'},null,2));return;}
 if(sub==='explain-route'){const task=process.argv[4];if(!task)throw new Error('TASK_REQUIRED');const governor=new InMemoryComputeGovernor(seed.pools),health=new ProviderHealthManager(),bench=new BenchmarkRegistry();for(const b of seed.benchmarks)bench.upsert(b);const gateway={execute:async ex=>({text:'DRY_RUN',receipt:{executionId:ex.executionId,providerId:ex.providerId,modelId:ex.modelId,inputTokens:1,outputTokens:1,usageUnits:2,latencyMs:1,finishReason:'dry',responseHash:await sha256('DRY_RUN'),providerQuotaHeadersNormalized:{},status:'SUCCESS',adapterVersion:'aria-model-gateway-v1',completedAt:now}})};const router=new ComputeMarketRouter(registry,seed.evidence,governor,health,bench,gateway);try{await router.route({taskId:task,role:'AUD',tier:'T1',taskClass:'BUSINESS_REASONING',dataClass:'PUBLIC',pii:false,prompt:'explain-route dry-run public fixture',requestedMaxOutputTokens:64,requiredCapabilities:['text'],reason:'CLI dry route'},now)}catch{}console.log(JSON.stringify(router.explainRoute(task)??{taskId:task,reason:'NO_SAFE_MODEL_ROUTE'},null,2));return;}
 throw new Error(`UNKNOWN_COMPUTE_SUBCOMMAND:${sub}`);}
if(command==='compute')await computeCli();else if(command==='doctor')run(['run','doctor']);else if(command==='benchmark')run(['run','benchmark']);else if(command==='export-evidence')run(['run','evidence']);else if(command==='ingest'){if((process.argv[3]??'reference')!=='reference')throw new Error('ONLY_REFERENCE_FIXTURE_SUPPORTED_LOCALLY');const state=await store.load(),ledger=new Ledger();ledger.replaceForTest(await store.loadLedger());const memory=new EventMemory(state,ledger);let duplicates=0;for(const event of await referenceEvents()){const r=await memory.ingest(event);if(r.duplicate)duplicates++}const projection=await rebuildProjection(state.events);state.leads=projection.leads;state.metrics=projection.metrics;await store.save(state);await store.saveLedger(ledger.list());console.log(JSON.stringify({events:state.events.length,duplicates,fixture:'REFERENCE_BUSINESS_FIXTURE'}));}else if(command==='run'){const task=process.argv[3]??'reference-e2e';if(task!=='reference-e2e')throw new Error('UNKNOWN_RUN_TASK');const o=new AriaOrchestrator(store,undefined,'local-reference-signing-key',()=>new Date('2026-08-19T15:00:00.000Z'));await o.load();const result=await o.runReferenceE2E(await referenceEvents(),new LocalEffectGateway());console.log(JSON.stringify({pass:result.steps.every(s=>s.pass),steps:result.steps.length,modelCalls:result.modelCalls,costUsd:result.costUsd},null,2));}else if(command==='tick'){const state=await store.load(),scheduler=new Scheduler(state),slot=new Date().toISOString(),result=await scheduler.enqueue('business_tick',slot.slice(0,16)+':00.000Z');await store.save(state);console.log(JSON.stringify({taskId:result.task.id,duplicate:result.duplicate,status:result.task.status}));}else if(command==='verify-ledger'){const ledger=new Ledger();ledger.replaceForTest(await store.loadLedger());console.log(JSON.stringify(await ledger.verify(),null,2));}else if(command==='replay'){const state=await store.load(),before=await stateHash(state),rebuilt=await rebuildProjection(state.events);state.leads=rebuilt.leads;state.metrics=rebuilt.metrics;const after=await stateHash(state);console.log(JSON.stringify({scope:process.argv[3]??'all',before,after,projectionEvents:state.events.length,deterministic:before===after},null,2));}else if(command==='compact-memory'){const state=await store.load(),ledger=new Ledger();ledger.replaceForTest(await store.loadLedger());const memory=new EventMemory(state,ledger),expired=memory.expire(new Date().toISOString());await store.save(state);console.log(JSON.stringify({expired,remaining:state.knowledge.filter(k=>k.status==='VERIFIED_KNOWLEDGE').length}));}else console.log('aria doctor | ingest reference | run reference-e2e | tick | replay [id] | verify-ledger | compact-memory | benchmark | export-evidence | compute status|providers|probe <provider>|benchmark|explain-route <task>|verify-cost|disable <id>|reconcile');
