import { sha256 } from "../../../packages/core/src/hash.js";
import type { InferenceExecution, InferenceReceipt } from "../../../packages/router/src/computeTypes.js";
import { containsSecret } from "../../../packages/router/src/computePolicy.js";
import { OpenAICompatibleProvider } from "../../../packages/router/src/adapters/openAiCompatible.js";
import { WorkersAiProvider } from "../../../packages/router/src/adapters/workersAi.js";
import type { ModelProvider, WorkersAiBinding } from "../../../packages/router/src/modelRouter.js";
import { findManifest, manifestConfigHash } from "./providerManifest.js";
interface ModelEnv{AI:WorkersAiBinding;GROQ_API_KEY?:string;MISTRAL_API_KEY?:string;GEMINI_API_KEY?:string;ZENMUX_API_KEY?:string;ARIA_GIT_SHA?:string;}
const ADAPTER_VERSION="aria-model-gateway-v1";
function json(body:unknown,status=200):Response{return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json","cache-control":"no-store","x-content-type-options":"nosniff"}});}
function credential(env:ModelEnv,name:string|undefined):string|undefined{return name?Reflect.get(env,name) as string|undefined:undefined;}
async function verifyExecution(execution:InferenceExecution,now:string):Promise<void>{if(execution.expiresAt<=now)throw new Error("EXPIRED_EXECUTION");if(execution.dataClass==="SECRET"||containsSecret(execution.prompt))throw new Error("SECRET_DATA_MODEL_DENIED");if(await sha256(execution.prompt)!==execution.promptHash)throw new Error("PROMPT_HASH_MISMATCH");const{executionDigest,...base}=execution;if(await sha256(base)!==executionDigest)throw new Error("EXECUTION_DIGEST_MISMATCH");const provider=findManifest(execution.providerId);if(!provider)throw new Error("UNKNOWN_PROVIDER");const model=provider.models.find(m=>m.modelId===execution.modelId);if(!model)throw new Error("UNKNOWN_MODEL");if(execution.maxOutputTokens>model.maxOutputTokens)throw new Error("MAX_OUTPUT_EXCEEDS_ROUTE");for(const capability of execution.requiredCapabilities)if(!model.capabilities.includes(capability))throw new Error("UNSUPPORTED_CAPABILITY");if(await manifestConfigHash(provider)!==execution.providerConfigHash)throw new Error("CONFIG_HASH_MISMATCH");}
function adapterFor(env:ModelEnv,providerId:string):{adapter:ModelProvider;credentialPresent:boolean}{const provider=findManifest(providerId);if(!provider)throw new Error("UNKNOWN_PROVIDER");if(provider.protocol==="WORKERS_AI_BINDING")return{adapter:new WorkersAiProvider(env.AI),credentialPresent:true};const key=credential(env,provider.credentialBindingName);if(!key)throw new Error("AUTH_INVALID");if(!provider.endpoint)throw new Error("ARBITRARY_BASE_URL");return{adapter:new OpenAICompatibleProvider({providerId:provider.providerId,baseUrl:provider.endpoint,apiKey:key,maxRetries:1,timeoutMs:15000,maxResponseBytes:1_000_000}),credentialPresent:true};}
function errorClass(message:string):NonNullable<InferenceReceipt["errorClass"]>{if(/BILLING_REQUIRED|402/.test(message))return"BILLING_REQUIRED";if(/AUTH_INVALID|401|403/.test(message))return"AUTH_INVALID";if(/RATE_LIMITED|FREE_QUOTA|429/.test(message))return"RATE_LIMITED";if(/MODEL_REMOVED|404/.test(message))return"MODEL_REMOVED";if(/PROVIDER_OUTAGE|timeout|5\d\d/i.test(message))return"PROVIDER_OUTAGE";return"MODEL_RESPONSE_INVALID";}
async function probe(env:ModelEnv,providerId:string,modelId:string):Promise<Response>{const provider=findManifest(providerId);if(!provider)return json({ok:false,error:"UNKNOWN_PROVIDER"},404);const model=provider.models.find(m=>m.modelId===modelId);if(!model)return json({ok:false,error:"UNKNOWN_MODEL"},404);let adapter:ModelProvider;try{adapter=adapterFor(env,providerId).adapter;}catch(error){return json({ok:false,providerId,modelId,credentialPresent:false,error:error instanceof Error?error.message:"AUTH_INVALID",valuesExposed:false},401);}const started=Date.now();try{const result=await adapter.run(modelId,"Return exactly the word OK.",8);const headers=result.quotaHeaders??{};return json({ok:true,providerId,modelId,credentialPresent:true,inputTokens:result.inputTokens,outputTokens:result.outputTokens,latencyMs:Date.now()-started,quotaHeadersNormalized:headers,responseHash:await sha256(result.text),billingSignal:"NO_BILLING_SIGNAL_OBSERVED",valuesExposed:false});}catch(error){const message=error instanceof Error?error.message:String(error);return json({ok:false,providerId,modelId,credentialPresent:true,error:errorClass(message),latencyMs:Date.now()-started,valuesExposed:false},/AUTH_INVALID/.test(message)?401:/BILLING_REQUIRED/.test(message)?402:/RATE_LIMITED/.test(message)?429:503);}}
export default{async fetch(request:Request,env:ModelEnv):Promise<Response>{const url=new URL(request.url);if(request.method==="GET"&&url.pathname==="/internal/health")return json({ok:true,worker:"aria-models",sha:env.ARIA_GIT_SHA??"unknown",providerCredentialPresence:{groq:Boolean(env.GROQ_API_KEY),mistral:Boolean(env.MISTRAL_API_KEY),gemini:Boolean(env.GEMINI_API_KEY),zenmux:Boolean(env.ZENMUX_API_KEY)},valuesExposed:false});if(request.method==="POST"&&url.pathname==="/internal/probe"){const body=await request.json() as{providerId?:string;modelId?:string};if(!body.providerId||!body.modelId)return json({error:"PROBE_SCHEMA_INVALID"},400);return probe(env,body.providerId,body.modelId);}if(request.method!=="POST"||url.pathname!=="/internal/infer")return new Response("NOT_FOUND",{status:404});const now=new Date().toISOString();try{const execution=await request.json() as InferenceExecution;await verifyExecution(execution,now);const provider=findManifest(execution.providerId)!;const model=provider.models.find(m=>m.modelId===execution.modelId)!;const adapter=adapterFor(env,execution.providerId).adapter;const started=Date.now();let result;try{result=await adapter.run(model.modelId,execution.prompt,execution.maxOutputTokens);}catch(error){const message=error instanceof Error?error.message:String(error),classified=errorClass(message);const receipt:InferenceReceipt={executionId:execution.executionId,providerId:execution.providerId,modelId:execution.modelId,inputTokens:0,outputTokens:0,usageUnits:0,latencyMs:Date.now()-started,finishReason:"error",responseHash:await sha256({errorClass:classified}),providerQuotaHeadersNormalized:{},status:"FAILED",errorClass:classified,adapterVersion:ADAPTER_VERSION,completedAt:new Date().toISOString()};return json({error:classified,receipt},classified==="BILLING_REQUIRED"?402:classified==="AUTH_INVALID"?401:classified==="RATE_LIMITED"?429:503);}if(result.outputTokens>execution.maxOutputTokens)throw new Error("MAX_OUTPUT_EXCEEDS_ROUTE");const receipt:InferenceReceipt={executionId:execution.executionId,providerId:execution.providerId,modelId:execution.modelId,...(result.providerRequestId?{providerRequestId:result.providerRequestId}:{}),inputTokens:result.inputTokens,outputTokens:result.outputTokens,usageUnits:result.usageUnits??(result.inputTokens+result.outputTokens),latencyMs:result.latencyMs,finishReason:result.finishReason??"stop",responseHash:await sha256(result.text),providerQuotaHeadersNormalized:result.quotaHeaders??{},status:"SUCCESS",adapterVersion:ADAPTER_VERSION,completedAt:new Date().toISOString()};return json({text:result.text,receipt,workerSha:env.ARIA_GIT_SHA??"unknown"});}catch(error){return json({error:error instanceof Error?error.message:"MODEL_GATEWAY_ERROR"},400);}}};
