import { sha256 } from "../../../packages/core/src/hash.js";
export interface ManifestModel{modelId:string;maxOutputTokens:number;capabilities:string[];}
export interface ManifestProvider{providerId:string;protocol:"WORKERS_AI_BINDING"|"OPENAI_COMPATIBLE";baseUrlId:string;endpoint?:string;credentialBindingName?:"GROQ_API_KEY"|"MISTRAL_API_KEY"|"GEMINI_API_KEY"|"ZENMUX_API_KEY";models:ManifestModel[];}
export const PROVIDER_MANIFEST:ManifestProvider[]=[
 {providerId:"cloudflare-workers-ai",protocol:"WORKERS_AI_BINDING",baseUrlId:"workers-ai-binding",models:[{modelId:"@cf/zai-org/glm-4.7-flash",maxOutputTokens:4096,capabilities:["text","structured"]},{modelId:"@cf/qwen/qwen3-30b-a3b-fp8",maxOutputTokens:4096,capabilities:["text","reasoning","structured"]},{modelId:"@cf/openai/gpt-oss-20b",maxOutputTokens:4096,capabilities:["text","coding","reasoning","structured"]},{modelId:"@cf/openai/gpt-oss-120b",maxOutputTokens:4096,capabilities:["text","reasoning","structured"]},{modelId:"@cf/nvidia/nemotron-3-120b-a12b",maxOutputTokens:4096,capabilities:["text","coding","reasoning"]}]},
 {providerId:"groq",protocol:"OPENAI_COMPATIBLE",baseUrlId:"groq-openai-v1",endpoint:"https://api.groq.com/openai/v1/chat/completions",credentialBindingName:"GROQ_API_KEY",models:[{modelId:"openai/gpt-oss-120b",maxOutputTokens:8192,capabilities:["text","reasoning","structured"]},{modelId:"openai/gpt-oss-20b",maxOutputTokens:8192,capabilities:["text","coding","reasoning","structured"]},{modelId:"llama-3.1-8b-instant",maxOutputTokens:4096,capabilities:["text","structured"]}]},
 {providerId:"mistral",protocol:"OPENAI_COMPATIBLE",baseUrlId:"mistral-openai-v1",endpoint:"https://api.mistral.ai/v1/chat/completions",credentialBindingName:"MISTRAL_API_KEY",models:[{modelId:"mistral-small-latest",maxOutputTokens:8192,capabilities:["text","reasoning","structured","coding"]}]},
 {providerId:"google-gemini",protocol:"OPENAI_COMPATIBLE",baseUrlId:"gemini-openai-v1beta",endpoint:"https://generativelanguage.googleapis.com/v1beta/openai/chat/completions",credentialBindingName:"GEMINI_API_KEY",models:[{modelId:"gemini-3.6-flash",maxOutputTokens:8192,capabilities:["text","reasoning","structured","tools","vision"]}]}
];
export function findManifest(providerId:string){return PROVIDER_MANIFEST.find(p=>p.providerId===providerId);}
export async function manifestConfigHash(provider:ManifestProvider):Promise<string>{return sha256({providerId:provider.providerId,baseUrlId:provider.baseUrlId,protocol:provider.protocol});}
